import 'package:flutter_test/flutter_test.dart';
import 'package:goldenscout/tool/astro.dart';

/// Cross-implementation fidelity gate against **SunCalc** (mourner/suncalc,
/// BSD-2-Clause), the industry-standard Meeus-based JS library. Our engine is a
/// Paul Schlyter low-precision port (see astro.dart); this file pins our output
/// to numbers produced independently by SunCalc so a mistyped coefficient or a
/// flipped sign is caught against an outside authority, not our own math.
///
/// Expected values were generated by running SunCalc v3 at
/// D:\toolapp\_ref\suncalc (getPosition / getTimes / getMoonIllumination) for
/// the dates/locations below and are transcribed here. See REFERENCE.md for the
/// per-formula comparison and the reasoning behind each tolerance.
///
/// Tolerances (from the audit brief): sunrise/sunset ≤ 1 min, azimuth ≤ 0.5°,
/// moon illuminated fraction ≤ 0.02. Both libraries solve rise/set as the
/// geometric-altitude crossing of −0.833° (refraction+radius baked into the
/// threshold, not into the position), so the times agree far tighter than 1 min
/// except near the solstice at high latitude where the Schlyter/Meeus
/// declination gap widens the window slightly.
void main() {
  // Our sunPosition/moonPosition return *geometric* altitude; SunCalc's
  // getPosition returns *apparent* (refraction added). At the mid/high
  // altitudes tested the difference is < 0.01°, well inside altAbs.
  const azTol = 0.5; // degrees
  const altTol = 0.2; // degrees (geometric vs apparent slack)
  const illumTol = 0.02;

  String hm(DateTime? t) => t == null
      ? '—'
      : '${t.hour.toString().padLeft(2, '0')}:${t.minute.toString().padLeft(2, '0')}';
  int mins(String v) =>
      int.parse(v.split(':')[0]) * 60 + int.parse(v.split(':')[1]);
  Matcher withinMin(String hhmm, {int minutes = 1}) => predicate<DateTime?>((t) {
        if (t == null) return false;
        return (mins(hm(t)) - mins(hhmm)).abs() <= minutes;
      }, 'within $minutes min of $hhmm');

  group('Sun horizontal position vs SunCalc (azimuth ≤0.5°)', () {
    test('New York, 2026-06-21 16:00Z → az 140.48°, alt 68.88°', () {
      final p = sunPosition(DateTime.utc(2026, 6, 21, 16), 40.7128, -74.0060);
      expect(p.azimuth, closeTo(140.4753, azTol));
      expect(p.altitude, closeTo(68.8844, altTol));
    });

    test('London, 2026-03-20 12:00Z (equinox) → az 177.45°, alt 38.44°', () {
      final p = sunPosition(DateTime.utc(2026, 3, 20, 12), 51.5074, -0.1278);
      expect(p.azimuth, closeTo(177.4538, azTol));
      expect(p.altitude, closeTo(38.4433, altTol));
    });

    test('New York sunrise instant 2026-06-21 09:25Z → az ≈ 57.5° (NE)', () {
      final p = sunPosition(DateTime.utc(2026, 6, 21, 9, 25), 40.7128, -74.0060);
      expect(p.azimuth, closeTo(57.4928, azTol));
      expect(compassLabel(p.azimuth), 'ENE');
    });
  });

  group('Sunrise/sunset & twilight times vs SunCalc (≤1 min)', () {
    // zoneOverride:zero keeps the sample frame in UTC so wall-clock == UTC and
    // we can compare directly against SunCalc's UTC ISO output.
    test('New York, 2026-06-21 (UTC): sunrise 09:25, sunset 00:30 (+1)', () {
      final d = computeDayLight(DateTime(2026, 6, 21), 40.7128, -74.0060,
          zoneOverride: Duration.zero);
      expect(d.sunrise.time, withinMin('09:25')); // SunCalc 09:25:02Z
      expect(d.sunset.time, withinMin('00:30')); // SunCalc 00:30:46Z (+1)
      expect(d.dayOffset(d.sunset.time!), 1);
      // Golden hour upper edge (+6°): am end 10:06Z, pm start 23:49Z.
      expect(d.goldenEndAm.time, withinMin('10:06'));
      expect(d.goldenStartPm.time, withinMin('23:49'));
      // Civil twilight (−6°): dawn 08:51Z, dusk 01:04Z (+1).
      expect(d.dawnCivil.time, withinMin('08:51'));
      expect(d.duskCivil.time, withinMin('01:04'));
    });

    test('London, 2026-06-21 (UTC): sunrise 03:43, sunset 20:21', () {
      final d = computeDayLight(DateTime(2026, 6, 21), 51.5074, -0.1278,
          zoneOverride: Duration.zero);
      expect(d.sunrise.time, withinMin('03:43')); // SunCalc 03:43:06Z
      expect(d.sunset.time, withinMin('20:21')); // SunCalc 20:21:35Z
    });
  });

  group('Solar-noon peak altitude vs SunCalc (≤0.2°)', () {
    test('New York, 2026-06-21 → 72.73°', () {
      final d = computeDayLight(DateTime(2026, 6, 21), 40.7128, -74.0060,
          zoneOverride: Duration.zero);
      expect(d.noonAltitude, closeTo(72.7301, altTol));
    });
    test('London, 2026-06-21 → 61.94°', () {
      final d = computeDayLight(DateTime(2026, 6, 21), 51.5074, -0.1278,
          zoneOverride: Duration.zero);
      expect(d.noonAltitude, closeTo(61.9397, altTol));
    });
  });

  group('Moon illuminated fraction vs SunCalc (≤0.02)', () {
    // getMoonIllumination(date).fraction from SunCalc.
    test('2026-06-21 00:00Z → 0.406 (waxing)', () {
      final m = moonPhase(DateTime.utc(2026, 6, 21));
      expect(m.illumination, closeTo(0.4061, illumTol));
      expect(m.waxing, isTrue);
    });
    test('2026-06-25 12:00Z → 0.826 (waxing gibbous)', () {
      final m = moonPhase(DateTime.utc(2026, 6, 25, 12));
      expect(m.illumination, closeTo(0.8261, illumTol));
      expect(m.waxing, isTrue);
    });
    test('2026-06-29 12:00Z → 0.996 (near full)', () {
      final m = moonPhase(DateTime.utc(2026, 6, 29, 12));
      expect(m.illumination, closeTo(0.9963, illumTol));
    });
    test('2026-07-10 00:00Z → 0.264 (waning)', () {
      final m = moonPhase(DateTime.utc(2026, 7, 10));
      expect(m.illumination, closeTo(0.2638, illumTol));
      expect(m.waxing, isFalse);
    });
  });
}
